import { useParams } from 'react-router-dom';
import Layout from '../components/Layout';
import { useKakuroGame } from '../features/kakuro/useKakuroGame';

export default function Kakuro() {
  const { userId } = useParams<{ userId: string }>();
  const game = useKakuroGame();
  const nums = Array.from({ length: 9 }, (_, i) => i + 1);
  return <Layout userId={userId || ''} showBack backTo={`/${userId}/brain`} maxWidth="max-w-3xl"><div className="py-4">
    <div className="text-center mb-5"><div className="text-5xl mb-2">🧩</div><h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">数和填字 Kakuro</h1><p className="text-sm text-gray-500 dark:text-gray-400 mt-2">空格填 1-9；每段数字和等于提示，且同一段不能重复。</p></div>
    <div className="flex gap-2 overflow-x-auto pb-3 mb-4">{game.levels.map((level, index) => <button key={level.id} onClick={() => game.chooseLevel(index)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-bold ${game.levelIndex === index ? 'bg-purple-600 text-white' : 'bg-white dark:bg-gray-900 text-gray-700 dark:text-gray-200'}`}>第{index + 1}关</button>)}</div>
    <div className="rounded-3xl bg-white dark:bg-gray-900 p-4 shadow-sm mb-4"><div className="flex items-center justify-between mb-3"><div><div className="font-bold text-gray-900 dark:text-gray-100">{game.puzzle.title}</div><div className="text-xs text-gray-500 dark:text-gray-400">右上数字是横向和，左下数字是纵向和。</div></div><button onClick={game.reset} className="text-sm text-gray-500 dark:text-gray-400 underline">清空</button></div>
      <div className="grid mx-auto w-full max-w-[390px] aspect-square border-2 border-gray-900 dark:border-gray-100 overflow-hidden" style={{ gridTemplateColumns: `repeat(${game.puzzle.cols}, minmax(0, 1fr))`, gridTemplateRows: `repeat(${game.puzzle.rows}, minmax(0, 1fr))` }}>{game.puzzle.cells.map((row, r) => row.map((cell, c) => cell.kind === 'block' ? <div key={`${r}-${c}`} className="relative bg-gray-800 dark:bg-gray-700 border border-gray-600 text-white text-[10px] font-bold overflow-hidden"><div className="absolute inset-0 bg-gradient-to-br from-transparent from-49% via-gray-500 via-50% to-transparent to-51%" />{cell.clue?.right && <span className="absolute top-1 right-1">{cell.clue.right}</span>}{cell.clue?.down && <span className="absolute bottom-1 left-1">{cell.clue.down}</span>}</div> : <button key={`${r}-${c}`} onClick={() => game.setSelected({ row: r, col: c })} className={`m-0.5 rounded-lg border-2 min-h-0 min-w-0 overflow-hidden flex items-center justify-center text-xl font-black leading-none ${game.selected?.row === r && game.selected?.col === c ? 'bg-purple-50 dark:bg-purple-900/20 border-purple-500' : 'bg-white dark:bg-gray-950 border-gray-300 dark:border-gray-700'} text-gray-900 dark:text-gray-100`}>{game.grid[r][c] ?? ''}</button>))}</div>
      <div className="grid grid-cols-5 gap-2 mt-4 max-w-[390px] mx-auto">{nums.slice(0,5).map(n => <button key={n} onClick={() => game.setCell(n)} className="rounded-2xl py-3 bg-purple-100 dark:bg-purple-900/30 text-purple-800 dark:text-purple-200 font-black text-xl">{n}</button>)}{nums.slice(5).map(n => <button key={n} onClick={() => game.setCell(n)} className="rounded-2xl py-3 bg-purple-100 dark:bg-purple-900/30 text-purple-800 dark:text-purple-200 font-black text-xl">{n}</button>)}<button onClick={() => game.setCell(null)} className="rounded-2xl py-3 bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-200 font-bold">擦除</button></div>
    </div>{game.result && <div className={`rounded-2xl p-4 mb-4 font-bold text-center ${game.result.ok ? 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-200' : 'bg-rose-100 text-rose-800 dark:bg-rose-900/30 dark:text-rose-200'}`}>{game.result.message}</div>}<button onClick={game.submit} className="w-full rounded-2xl bg-purple-600 text-white py-4 font-bold shadow-lg">提交答案</button>
  </div></Layout>;
}
